version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
files:
  - source: /img
    destination: /var/www/html/img
hooks:
  BeforeInstall:
    - location: deploy/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/restart_server
      timeout: 300
      runas: root